Algoritmo "EXERCICIO 7"

// Feito por: Gustavo Abreu

Var

num1,num2,multi,soma,divi,sub : real

Inicio
Escreval("Digite o primeiro número: ")
leia(num1)
escreval("Digite o segundo número: ")
leia(num2)

multi <- (num1 * num2)
soma <- (num1 + num2)
divi <- (num1 / num2)
sub <- (num1 - num2)


escreval("===================================")
escreval("Multiplicação: ", multi)
escreval("Soma: ", soma)
escreval("Divisão: ", divi)
escreval("Subtração: ", sub)
escreval("===================================")

Fimalgoritmo