Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
largura:real
altura:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 21=====")
Escreva("Qual é a largura do retângulo: ")
Leia(largura)
Escreva("Qual é a altura do retângulo: ")
Leia(altura)
area <- largura * altura
Escreval("A área do retângulo é: ", area)
Fimalgoritmo