Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
distancia:real
litros:real
consumo:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 31=====")
escreva("Qual é a distância percorrida em km: ")
leia(distancia)
escreva("Qual é a quantidade de combustível consumida em litros: ")
leia(litros)
consumo <- distancia / litros
escreval("O gasto médio do veículo é foi de: ", consumo:1:2, " km/L")

Fimalgoritmo