Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
horas, minutos: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite suas horas: ")
leia(horas)

minutos <- horas * 60

escreval("A quantidade de minutos é: ", minutos)

Fimalgoritmo