Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
media1, media2, media3, medialuno: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a primeira média: ")
leia(media1)

escreva("Digite a segunda média: ")
leia(media2)

escreva("Digite a terceira média: ")
leia(media3)

medialuno <- (media1 + media2 + media3) / 3

escreval("A média desse aluno é: ",medialuno)

Fimalgoritmo