Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
quilometros:real
metros:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 18=====")
escreva("Qual foi a distância percorrida em quilômetros: ")
leia(quilometros)
metros <- quilometros * 1000
escreval("A distância percorrida foi de aproximadamente", metros, " m.")
Fimalgoritmo