Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
pesokg, pesogramas: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o peso em kg: ")
leia(pesokg)

pesogramas <- pesokg * 1000

escreval("O peso em gramas é: ",pesogramas)

Fimalgoritmo