algoritmo "exercicio 12"

var

  numero_1,numero_2 :real

inicio
  escreval ("--------------------")
  escreval ("   SOMA E PRODUTO   ")
  escreval ("--------------------")
  escreval ("Digite o primeiro numero: ")
  leia (numero_1)
  escreval ("Digite o segundo numero: ")
  leia (numero_2)
  escreval (numero_1," + ",numero_2," = ",numero_1 + numero_2)
  escreval (numero_1," - ",numero_2," = ",numero_1 - numero_2)
fimalgoritmo