Algoritmo "semnome"
// Feito por katarina
Var
// Seção de Declarações das variáveis 
num1, num2, num3, soma: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o primeiro número: ")
leia(num1)

escreva("Digite o segundo número: ")
leia(num2)

escreva("Digite o terceiro número: ")
leia(num3)

soma <- num1 + num2 + num3

escreval("O resultado da soma de números inteiros é: ",soma)

Fimalgoritmo
