Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a base do triângulo: ")
leia(base)

escreva("Digite a altura do triângulo: ")
leia(altura)

area <- (base * altura) / 2

escreval("A área desse triângulo é: ", area)

Fimalgoritmo