Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
numero1:real
numero2:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 7=====")
escreva("Digite o primeiro número: ")
leia(numero1)
escreva("Digite o segundo número: ")
leia(numero2)
escreval("===============")
escreval("Soma: ", numero1 + numero2)
escreval("Subtração: ", numero1 - numero2)
escreval("Multiplicação: ", numero1 * numero2)
escreval("divisão: ", numero1 / numero2)
Fimalgoritmo