Algoritmo "semnome"
// Feito por katarina
Var
// Seção de Declarações das variáveis 
valortotal, valorporpessoa: real
pessoas: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor total da conta do restaurante: ")
leia(valortotal)

escreva("Quantas pessoas vão dividir a conta: ")
leia(pessoas)

valorporpessoa <- valortotal / pessoas

escreval("O que cada pessoa deve pagar é: ",valorporpessoa)

Fimalgoritmo
