Algoritmo "Exercício 25"
// Feito por: Gustavo Abreu


Var

nome : caracter
preco, total: real
qntd_comprada: inteiro

Inicio
Escreval("Digite o nome do produto: ")
leia(nome)

Escreval("Digite o preço unitário do produto: ")
leia(preco)

Escreval("Digite a quantidade adquirida: ")
leia(qntd_comprada)

total <- preco * qntd_comprada

Escreval(qntd_comprada," unidades do produto: ", nome , " custará: ",total, " R$")


Fimalgoritmo