Algoritmo "EXERCICIO 2"

// Feito por: Gustavo Abreu

Var
nome, cidade : caracter
idade: inteiro

Inicio
Escreval("Digite seu nome: ")
leia(nome)

Escreval("Digite sua idade: ")
leia(idade)

Escreval("Em qual cidade você reside?: ")
leia(cidade)

escreval("")
escreval("===================================")
Escreval("Nome: ", nome)
escreval("Idade: ", idade)
escreval("Cidade: ", cidade)
escreval("===================================")


Fimalgoritmo