Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
nome : caractere
idade : inteiro
cidade : caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 1=====")
escreva("Qual é o seu nome: ")
leia(nome)
escreva("Qual é a sua idade: ")
leia(idade)
escreva("Qual é a sua cidade: ")
leia(cidade)
escreval("======================")
escreval("Nome: ", nome)
escreval("Idade: ", idade, " anos")
escreval("Cidade: ", cidade)
Fimalgoritmo