Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
num, dobro, triplo: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número inteiro: ")
leia(num)

dobro <- num * 2

triplo <- num * 3

escreval("O dobro desse número é: ",dobro)

escreval("O triplo desse número é: ",triplo)

Fimalgoritmo