Algoritmo "semnome"
//Aluno:Cristiano Ronaldo
Var
// Seção de Declarações das variáveis 
 A:Inteiro
 B:Inteiro
 auxiliar:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("=====EXERCICIO 36=====")
Escreva("Qual o valor de A: ")
Leia(A)
Escreva("Qual o valor de B: ")
Leia(B)
escreval("")
escreval("Antes da troca:")
escreval("A =", A)
escreval("B =", B)
auxiliar <- A
A <- B
B <- auxiliar
escreval("")
escreval("Depois da troca:")
escreval("A =", A)
escreval("B =", B)
Fimalgoritmo